# Pandas for Data Science Interviews

This notebook aims to provide a quick reference for common Pandas operations that are frequently encountered in data science and data engineering interviews. Mastering these concepts will help you manipulate and analyze data efficiently.

## 1. Importing Pandas and Loading Data

The first step in almost any data manipulation task with Pandas is to import the library and load your data into a DataFrame. We'll simulate loading a CSV file.

In [2]:
import pandas as pd
import numpy as np # Often used alongside pandas

# Create a dummy CSV file for demonstration
data = {
    'ProductID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Category': ['Electronics', 'Clothing', 'Electronics', 'Home Goods', 'Clothing', 'Electronics', 'Home Goods', 'Clothing', 'Electronics', 'Home Goods'],
    'Price': [1200, 50, 800, 150, 75, 950, 200, 60, 1100, 250],
    'Quantity': [10, 200, 15, 30, 120, 12, 25, 150, 8, 40],
    'Sales': [12000, 10000, 12000, 4500, 9000, 11400, 5000, 9000, 8800, 10000],
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West'],
    'Date': pd.to_datetime(['2023-01-01', '2023-01-01', '2023-01-02', '2023-01-02', '2023-01-03', '2023-01-03', '2023-01-04', '2023-01-04', '2023-01-05', '2023-01-05'])
}
df = pd.DataFrame(data)

# Introduce some missing values for demonstration
df.loc[[1, 5], 'Price'] = np.nan
df.loc[7, 'Category'] = np.nan

print("Original DataFrame:")
display(df.head())

Original DataFrame:

   ProductID     Category   Price  Quantity  Sales Region       Date
0          1  Electronics  1200.0        10  12000   East 2023-01-01
1          2     Clothing     NaN       200  10000   West 2023-01-01
2          3  Electronics   800.0        15  12000  North 2023-01-02
3          4   Home Goods   150.0        30   4500  South 2023-01-02
4          5     Clothing    75.0       120   9000   East 2023-01-03

In [3]:
id(data)

135579274070656

In [4]:
len(data)

7

In [5]:
data.get('Category')

['Electronics',
 'Clothing',
 'Electronics',
 'Home Goods',
 'Clothing',
 'Electronics',
 'Home Goods',
 'Clothing',
 'Electronics',
 'Home Goods']

In [6]:
data.keys()

dict_keys(['ProductID', 'Category', 'Price', 'Quantity', 'Sales', 'Region', 'Date'])

In [7]:
df.isnull()

   ProductID  Category  Price  Quantity  Sales  Region   Date
0      False     False  False     False  False   False  False
1      False     False   True     False  False   False  False
2      False     False  False     False  False   False  False
3      False     False  False     False  False   False  False
4      False     False  False     False  False   False  False
5      False     False   True     False  False   False  False
6      False     False  False     False  False   False  False
7      False      True  False     False  False   False  False
8      False     False  False     False  False   False  False
9      False     False  False     False  False   False  False

In [8]:
df.isnull().sum()

ProductID    0
Category     1
Price        2
Quantity     0
Sales        0
Region       0
Date         0
dtype: int64

In [9]:
df.head( )

   ProductID     Category   Price  Quantity  Sales Region       Date
0          1  Electronics  1200.0        10  12000   East 2023-01-01
1          2     Clothing     NaN       200  10000   West 2023-01-01
2          3  Electronics   800.0        15  12000  North 2023-01-02
3          4   Home Goods   150.0        30   4500  South 2023-01-02
4          5     Clothing    75.0       120   9000   East 2023-01-03

In [10]:
df[:3]

   ProductID     Category   Price  Quantity  Sales Region       Date
0          1  Electronics  1200.0        10  12000   East 2023-01-01
1          2     Clothing     NaN       200  10000   West 2023-01-01
2          3  Electronics   800.0        15  12000  North 2023-01-02

In [11]:
df[1:5]

   ProductID     Category  Price  Quantity  Sales Region       Date
1          2     Clothing    NaN       200  10000   West 2023-01-01
2          3  Electronics  800.0        15  12000  North 2023-01-02
3          4   Home Goods  150.0        30   4500  South 2023-01-02
4          5     Clothing   75.0       120   9000   East 2023-01-03

In [12]:
df[0:10:2]

   ProductID     Category   Price  Quantity  Sales Region       Date
0          1  Electronics  1200.0        10  12000   East 2023-01-01
2          3  Electronics   800.0        15  12000  North 2023-01-02
4          5     Clothing    75.0       120   9000   East 2023-01-03
6          7   Home Goods   200.0        25   5000  North 2023-01-04
8          9  Electronics  1100.0         8   8800   East 2023-01-05

In [13]:
df.columns

Index(['ProductID', 'Category', 'Price', 'Quantity', 'Sales', 'Region',
       'Date'],
      dtype='object')

In [14]:
df.tail()

   ProductID     Category   Price  Quantity  Sales Region       Date
5          6  Electronics     NaN        12  11400   West 2023-01-03
6          7   Home Goods   200.0        25   5000  North 2023-01-04
7          8          NaN    60.0       150   9000  South 2023-01-04
8          9  Electronics  1100.0         8   8800   East 2023-01-05
9         10   Home Goods   250.0        40  10000   West 2023-01-05

In [15]:
df.isna()

   ProductID  Category  Price  Quantity  Sales  Region   Date
0      False     False  False     False  False   False  False
1      False     False   True     False  False   False  False
2      False     False  False     False  False   False  False
3      False     False  False     False  False   False  False
4      False     False  False     False  False   False  False
5      False     False   True     False  False   False  False
6      False     False  False     False  False   False  False
7      False      True  False     False  False   False  False
8      False     False  False     False  False   False  False
9      False     False  False     False  False   False  False

## 2. Basic Data Inspection

Interviewers often test your ability to quickly understand a dataset. These methods are crucial for initial exploration.

In [16]:
print("\nDataFrame Info (data types, non-null counts):")
df.info()

print("\nDataFrame Description (summary statistics for numerical columns):")
display(df.describe())

print("\nDataFrame Shape (rows, columns):")
print(df.shape)

print("\nColumn names:")
print(df.columns)

DataFrame Info (data types, non-null counts):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ProductID  10 non-null     int64
 1   Category   9 non-null      object
 2   Price      8 non-null      float64
 3   Quantity   10 non-null     int64
 4   Sales      10 non-null     int64
 5   Region     10 non-null     object
 6   Date       10 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(3), object(2)
memory usage: 692.0+ bytes

DataFrame Description (summary statistics for numerical columns):

       ProductID        Price    Quantity         Sales                 Date
count   10.00000     8.000000   10.000000     10.000000                   10
mean     5.50000   479.375000   61.000000   9170.000000  2023-01-03 00:00:00
min      1.00000    60.000000    8.000000   4500.000000  2023-01-01 00:00:00
25%      3.25000   131.250000   12.750000   8850.000000  2023-01-02 00:00:00
50%      5.50000   225.000000   27.500000   9500.000000  2023-01-03 00:00:00
75%      7.75000   875.000000  100.000000  11050.000000  2023-01-04 00:00:00
max     10.00000  1200.000000  200.000000  12000.000000  2023-01-05 00:00:00
std      3.02765   475.968468   69.400608   2619.605568                  NaN

DataFrame Shape (rows, columns):
(10, 7)

Column names:
Index(['ProductID', 'Category', 'Price', 'Quantity', 'Sales', 'Region',
       'Date'],
      dtype='object')

## 3. Handling Missing Values

Dealing with `NaN` (Not a Number) values is a common interview topic.

In [17]:
print("\nMissing values count per column:")
print(df.isnull().sum())

# Option 1: Drop rows with any missing values
df_dropped = df.dropna()
print("\nDataFrame after dropping rows with missing values:")
display(df_dropped.head())

# Option 2: Fill missing numerical values with the mean
df_filled_mean = df.copy()
df_filled_mean['Price'] = df_filled_mean['Price'].fillna(df_filled_mean['Price'].mean())
print("\nDataFrame after filling Price with mean:")
display(df_filled_mean.head())

# Option 3: Fill missing categorical values with the mode
df_filled_mode = df.copy()
df_filled_mode['Category'] = df_filled_mode['Category'].fillna(df_filled_mode['Category'].mode()[0])
print("\nDataFrame after filling Category with mode:")
display(df_filled_mode.head())

Missing values count per column:
ProductID    0
Category     1
Price        2
Quantity     0
Sales        0
Region       0
Date         0
dtype: int64

DataFrame after dropping rows with missing values:

   ProductID     Category   Price  Quantity  Sales Region       Date
0          1  Electronics  1200.0        10  12000   East 2023-01-01
2          3  Electronics   800.0        15  12000  North 2023-01-02
3          4   Home Goods   150.0        30   4500  South 2023-01-02
4          5     Clothing    75.0       120   9000   East 2023-01-03
6          7   Home Goods   200.0        25   5000  North 2023-01-04

DataFrame after filling Price with mean:

   ProductID     Category     Price  Quantity  Sales Region       Date
0          1  Electronics  1200.000        10  12000   East 2023-01-01
1          2     Clothing   479.375       200  10000   West 2023-01-01
2          3  Electronics   800.000        15  12000  North 2023-01-02
3          4   Home Goods   150.000        30   4500  South 2023-01-02
4          5     Clothing    75.000       120   9000   East 2023-01-03

DataFrame after filling Category with mode:

   ProductID     Category   Price  Quantity  Sales Region       Date
0          1  Electronics  1200.0        10  12000   East 2023-01-01
1          2     Clothing     NaN       200  10000   West 2023-01-01
2          3  Electronics   800.0        15  12000  North 2023-01-02
3          4   Home Goods   150.0        30   4500  South 2023-01-02
4          5     Clothing    75.0       120   9000   East 2023-01-03

## 4. Filtering and Selecting Data

Selecting specific rows or columns based on conditions is fundamental.

In [18]:
print("\nSelect 'ProductID' and 'Sales' columns:")
display(df[['ProductID', 'Sales']].head())

print("\nFilter rows where 'Sales' > 10000:")
display(df[df['Sales'] > 10000])

print("\nFilter rows for 'Electronics' category and Price > 900:")
display(df[(df['Category'] == 'Electronics') & (df['Price'] > 900)])

print("\nSelect rows using `.loc` (label-based indexing) and `.iloc` (integer-location based indexing):")
display(df.loc[0:2, ['ProductID', 'Price']]) # First 3 rows, ProductID and Price columns
display(df.iloc[0:3, [0, 2]]) # First 3 rows, first and third columns

Select 'ProductID' and 'Sales' columns:

   ProductID  Sales
0          1  12000
1          2  10000
2          3  12000
3          4   4500
4          5   9000

Filter rows where 'Sales' > 10000:

   ProductID     Category   Price  Quantity  Sales Region       Date
0          1  Electronics  1200.0        10  12000   East 2023-01-01
2          3  Electronics   800.0        15  12000  North 2023-01-02
5          6  Electronics     NaN        12  11400   West 2023-01-03

Filter rows for 'Electronics' category and Price > 900:

   ProductID     Category   Price  Quantity  Sales Region       Date
0          1  Electronics  1200.0        10  12000   East 2023-01-01
8          9  Electronics  1100.0         8   8800   East 2023-01-05

Select rows using `.loc` (label-based indexing) and `.iloc` (integer-location based indexing):

   ProductID   Price
0          1  1200.0
1          2     NaN
2          3   800.0

   ProductID   Price
0          1  1200.0
1          2     NaN
2          3   800.0

## 5. Grouping and Aggregation

Summarizing data by groups is a very common task in data analysis.

In [19]:
print("\nTotal Sales by Category:")
display(df.groupby('Category')['Sales'].sum())

print("\nAverage Price and Total Quantity by Region:")
display(df.groupby('Region').agg(AveragePrice=('Price', 'mean'), TotalQuantity=('Quantity', 'sum')))

print("\nSales by Date and Category:")
display(df.groupby(['Date', 'Category'])['Sales'].sum().unstack())

Total Sales by Category:

Category
Clothing       19000
Electronics    44200
Home Goods     19500
Name: Sales, dtype: int64

Average Price and Total Quantity by Region:

        AveragePrice  TotalQuantity
Region
East      791.666667            138
North     500.000000             40
South     105.000000            180
West      250.000000            252

Sales by Date and Category:

Category    Clothing  Electronics  Home Goods
Date
2023-01-01   10000.0      12000.0         NaN
2023-01-02       NaN      12000.0      4500.0
2023-01-03    9000.0      11400.0         NaN
2023-01-04       NaN          NaN      5000.0
2023-01-05       NaN       8800.0     10000.0

## 6. Merging/Joining DataFrames

Combining data from multiple sources is a frequent requirement.

In [20]:
# Create another dummy DataFrame for product details
product_details = pd.DataFrame({
    'ProductID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Description': ['Laptop', 'T-shirt', 'Monitor', 'Chair', 'Jeans', 'Headphones', 'Table', 'Dress', 'Smartphone', 'Lamp'],
    'Manufacturer': ['A', 'B', 'A', 'C', 'B', 'A', 'C', 'B', 'A', 'C']
})
print("\nProduct Details DataFrame:")
display(product_details.head())

# Perform an inner merge based on 'ProductID'
merged_df = pd.merge(df, product_details, on='ProductID', how='inner')
print("\nMerged DataFrame (df with product_details):")
display(merged_df.head())

# Example of a left merge
customer_ratings = pd.DataFrame({
    'ProductID': [1, 3, 5, 11], # Product 11 does not exist in df
    'Rating': [4.5, 3.8, 4.9, 2.0]
})
print("\nCustomer Ratings DataFrame:")
display(customer_ratings.head())

left_merged_df = pd.merge(df, customer_ratings, on='ProductID', how='left')
print("\nLeft Merged DataFrame (df with customer_ratings):")
display(left_merged_df)

Product Details DataFrame:

   ProductID Description Manufacturer
0          1      Laptop            A
1          2     T-shirt            B
2          3     Monitor            A
3          4       Chair            C
4          5       Jeans            B

Merged DataFrame (df with product_details):

,ProductID,Category,Price,Quantity,Sales,Region,Date,Description,Manufacturer
0,1,Electronics,1200.0,10,12000,East,2023-01-01,Laptop,A
1,2,Clothing,NaN,200,10000,West,2023-01-01,T-shirt,B
2,3,Electronics,800.0,15,12000,North,2023-01-02,Monitor,A
3,4,Home Goods,150.0,30,4500,South,2023-01-02,Chair,C
4,5,Clothing,75.0,120,9000,East,2023-01-03,Jeans,B

Customer Ratings DataFrame:

   ProductID  Rating
0          1     4.5
1          3     3.8
2          5     4.9
3         11     2.0

Left Merged DataFrame (df with customer_ratings):

   ProductID     Category   Price  Quantity  Sales Region       Date  Rating
0          1  Electronics  1200.0        10  12000   East 2023-01-01     4.5
1          2     Clothing     NaN       200  10000   West 2023-01-01     NaN
2          3  Electronics   800.0        15  12000  North 2023-01-02     3.8
3          4   Home Goods   150.0        30   4500  South 2023-01-02     NaN
4          5     Clothing    75.0       120   9000   East 2023-01-03     4.9
5          6  Electronics     NaN        12  11400   West 2023-01-03     NaN
6          7   Home Goods   200.0        25   5000  North 2023-01-04     NaN
7          8          NaN    60.0       150   9000  South 2023-01-04     NaN
8          9  Electronics  1100.0         8   8800   East 2023-01-05     NaN
9         10   Home Goods   250.0        40  10000   West 2023-01-05     NaN

This notebook covers some of the most essential Pandas operations for data analysis and manipulation. Practicing these will significantly boost your confidence in data science interviews.

## Introduce statistical concept in Pandas ==

In [21]:
df.describe()

       ProductID        Price    Quantity         Sales                 Date
count   10.00000     8.000000   10.000000     10.000000                   10
mean     5.50000   479.375000   61.000000   9170.000000  2023-01-03 00:00:00
min      1.00000    60.000000    8.000000   4500.000000  2023-01-01 00:00:00
25%      3.25000   131.250000   12.750000   8850.000000  2023-01-02 00:00:00
50%      5.50000   225.000000   27.500000   9500.000000  2023-01-03 00:00:00
75%      7.75000   875.000000  100.000000  11050.000000  2023-01-04 00:00:00
max     10.00000  1200.000000  200.000000  12000.000000  2023-01-05 00:00:00
std      3.02765   475.968468   69.400608   2619.605568                  NaN

In [22]:
df.columns

Index(['ProductID', 'Category', 'Price', 'Quantity', 'Sales', 'Region',
       'Date'],
      dtype='object')

In [25]:
df['Category']

0    Electronics
1       Clothing
2    Electronics
3     Home Goods
4       Clothing
5    Electronics
6     Home Goods
7            NaN
8    Electronics
9     Home Goods
Name: Category, dtype: object

In [28]:
df[['Category','Price','Sales']]

      Category   Price  Sales
0  Electronics  1200.0  12000
1     Clothing     NaN  10000
2  Electronics   800.0  12000
3   Home Goods   150.0   4500
4     Clothing    75.0   9000
5  Electronics     NaN  11400
6   Home Goods   200.0   5000
7          NaN    60.0   9000
8  Electronics  1100.0   8800
9   Home Goods   250.0  10000

# Can you divide the dataset into categorical & numerical

In [29]:
df.columns

Index(['ProductID', 'Category', 'Price', 'Quantity', 'Sales', 'Region',
       'Date'],
      dtype='object')

In [30]:
data_cat = df[['ProductID', 'Category', 'Region']]
data_cat
#data_num

   ProductID     Category Region
0          1  Electronics   East
1          2     Clothing   West
2          3  Electronics  North
3          4   Home Goods  South
4          5     Clothing   East
5          6  Electronics   West
6          7   Home Goods  North
7          8          NaN  South
8          9  Electronics   East
9         10   Home Goods   West

In [31]:
data_cat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ProductID  10 non-null     int64
 1   Category   9 non-null      object
 2   Region     10 non-null     object
dtypes: int64(1), object(2)
memory usage: 372.0+ bytes

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ProductID  10 non-null     int64
 1   Category   9 non-null      object
 2   Price      8 non-null      float64
 3   Quantity   10 non-null     int64
 4   Sales      10 non-null     int64
 5   Region     10 non-null     object
 6   Date       10 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(3), object(2)
memory usage: 692.0+ bytes

In [34]:
len(data_cat.columns)

3

In [35]:
len(df.columns)

7

In [32]:
data_num = df[['Price', 'Quantity', 'Sales']]
data_num

    Price  Quantity  Sales
0  1200.0        10  12000
1     NaN       200  10000
2   800.0        15  12000
3   150.0        30   4500
4    75.0       120   9000
5     NaN        12  11400
6   200.0        25   5000
7    60.0       150   9000
8  1100.0         8   8800
9   250.0        40  10000

In [36]:
data_num.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Price     8 non-null      float64
 1   Quantity  10 non-null     int64
 2   Sales     10 non-null     int64
dtypes: float64(1), int64(2)
memory usage: 372.0 bytes

In [37]:
data_cat.describe()

       ProductID
count   10.00000
mean     5.50000
std      3.02765
min      1.00000
25%      3.25000
50%      5.50000
75%      7.75000
max     10.00000